FROM ubuntu
RUN apt update && apt install -y --no-install-recommends \
    curl \
    nano \
    net-tools iputils-ping \
    sudo \
    openssh-server 

RUN mkdir /root/admin/base
WORKDIR /root/admin/base
COPY ./dockerfiles/ubbase/admin/ .

COPY ./common/id_rsa.pub ./common/id_rsa.pub
RUN chmod +x ./start.sh

ENTRYPOINT [ "./start.sh" ]
